# Please Set VCS_HOME env 
set env(WORKDIR) $env(PWD)
database create db0 -technology HAPS-100
#Creates the HAPS-100 Database with name "db0"
launch uc -utf run.utf -ucdb ucdb -v 2.0
#launches UC on run.utf which calls vcs_dut.csh script and creates UC database(ucdb)# Please Set VCS_HOME env 
set env(WORKDIR) $env(PWD)
database create db0 -technology HAPS-100
#Creates the HAPS-100 Database with name "db0"
launch uc -utf run.utf -ucdb ucdb -v 2.0
#launches UC on run.utf which calls vcs_dut.csh script and creates UC database(ucdb)
run compile -ucdb ucdb  -out c0
#Runs compile using database generated by launch uc command

run pre_partition -fdc test.fdc -tss board.tss -out pp0_2F
#run partition -report_multi_hop_nets 1 -setup ps1 -pcf test.pcf -out pa0_2F
run partition -report_multi_hop_nets 1 -optimization_priority slack -clock_gate_replication 1 -pcf test.pcf -pcf /projects/prj1/kaoua/PC_TOOLS/PC_2025.06-1/protocomp/V-2025.06-1/lib/aptn/setup/ps1/setup_partition.pcf -out pa0_2F

run system_route -report_direct_nets 1 -report_timing_paths 1024 -report_unrouted_nets 1024 -optimization_priority slack -pcf test.pcf -pcf /projects/prj1/kaoua/PC_TOOLS/PC_2025.06-1/protocomp/V-2025.06-1/lib/aptn/setup/ps1/setup_partition.pcf -out sr0_2F

#run system_route -fdc test.fdc -pcf test.pcf -out sr0_2F

run system_generate -fdc test.fdc  -path synthesis_files_2F -out sg0_2F

launch protocompiler -parallel 4 -tclcmd {set ENABLE_PAR 1} -script [database query_state -script]
 
#launch protocompiler  -tclcmd {set VIVADO_VERILOG_FLOW 1; set ENABLE_PAR 1} -script synthesis_files_2F/mb1_uA/mb1_uA_srs.tcl -tclcmd {set VIVADO_VERILOG_FLOW 1; set ENABLE_PAR 1} -script synthesis_files_2F/mb1_uB/mb1_uB_srs.tcl

