# Please Set VCS_HOME env 
set env(WORKDIR) $env(PWD)
database create db0 -technology HAPS-100
#Creates the HAPS-100 Database with name "db0"
launch uc -utf run.utf -ucdb ucdb -v 2.0
#launches UC on run.utf which calls vcs_dut.csh script and creates UC database(ucdb)
run compile -ucdb ucdb  -out c0
#Runs compile using database generated by launch uc command

